#!/bin/sh

if [[ $SKIP_POST_CHECKOUT = 1 ]]
then
  echo "Skipping post checkout script"

  exit 0
fi

echo "Running post checkout script..."

php artisan optimize:clear
composer install --ignore-platform-reqs
